version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:10.14-browsers
    working_directory: /home/circleci/project
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            yarn install 
            cd client && yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      # Build
      - deploy:
          name: Build
          command: yarn build
      # End-to-end tests
      - run:
          name: Run e2e tests
          command: yarn testE2E
